import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const source = readFileSync(new URL('../.github/workflows/acceptance-audit.md', import.meta.url), 'utf8');
const lock = readFileSync(new URL('../.github/workflows/acceptance-audit.lock.yml', import.meta.url), 'utf8');
const frontmatter = source.split('\n---\n')[0];
const script = frontmatter.split('      script: |\n')[1].split('\n').map(line => line.slice(8)).join('\n');
const head = 'a'.repeat(40);
const title = `acceptance-audit/29/${head}`;
async function preflight({ pr = '29', sha = head, actualHead = head, runs = [], error, full = false } = {}) {
  let calls = 0;
  const github = { rest: {
    pulls: { get: async () => { calls++; if (error) throw error; return { data: { head: { sha: actualHead } } }; } },
    actions: {
      getWorkflowRun: async () => ({ data: { workflow_id: 42 } }),
      listWorkflowRuns: async () => { calls++; return { data: { workflow_runs: full ? Array.from({ length: 100 }, (_, i) => ({ id: i + 50 })) : runs } }; }
    }
  } };
  await vm.runInNewContext(`(async () => {${script}\n})()`, {
    process: { env: { AUDIT_PR: pr, AUDIT_HEAD: sha } }, github,
    context: { repo: { owner: 'kejun', repo: 'hearwise' }, runId: 7 }
  });
  return calls;
}

test('audit is manual, staged, bounded and generated by the patched compiler', () => {
  assert.match(frontmatter, /workflow_dispatch:/);
  assert.doesNotMatch(frontmatter, /^  (schedule|pull_request|pull_request_target|push|issue_comment):/m);
  assert.match(frontmatter, /staged: true/);
  assert.match(frontmatter, /max: 1/);
  assert.match(frontmatter, /max-turns: 12/);
  assert.match(frontmatter, /max-ai-credits: 10/);
  assert.match(frontmatter, /bash: false/);
  assert.match(frontmatter, /cli-proxy: false/);
  assert.match(lock, /"compiler_version":"v0\.89\.21"/);
  assert.doesNotMatch(lock, /^\s+[a-z-]+: write\s*$/m);
  assert.match(lock, /GH_AW_SAFE_OUTPUTS_STAGED: ["']?true/);
  assert.match(lock, /GH_AW_FAILURE_REPORT_AS_ISSUE: "false"/);
});

test('preflight accepts an exact PR head and empty audit history', async () => {
  assert.equal(await preflight(), 2);
});
for (const [name, options, expected] of [
  ['invalid PR', { pr: '29; echo injected' }, /positive PR number/],
  ['noncanonical SHA', { sha: 'main' }, /40-character/],
  ['stale head', { actualHead: 'b'.repeat(40) }, /head changed/],
  ['duplicate successful preview', { runs: [{ id: 3, display_title: title }] }, /already has a successful preview/],
  ['inaccessible source', { error: new Error('API unavailable') }, /API unavailable/],
  ['unbounded history', { full: true }, /history exceeds/]
]) test(`preflight fails closed: ${name}`, async () => { await assert.rejects(preflight(options), expected); });

test('different head and the current run are not mistaken for duplicates', async () => {
  await preflight({ runs: [{ id: 7, display_title: title }, { id: 2, display_title: `acceptance-audit/29/${'b'.repeat(40)}` }] });
});

test('pilot contract distinguishes PR29-style UI gaps from docs-only scope', () => {
  for (const phrase of ['Verified CI', 'Author-reported tests', 'Static coverage', 'Unrun or unverified coverage',
    'at most three', 'docs-only changes', 'do not demand', 'not proof of execution', 'Mock providers and fake media',
    'if changed, stop with noop', 'CodeRabbit']) assert.ok(source.includes(phrase), phrase);
});
